[package]
name = "bm-rs"
version = "0.1.0"
authors = ["nekogda <nekogda@>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# [profile.bench]
# opt-level = 0
